<?php

namespace backend\modules\circulation\controllers;
use backend\modules\circulation\models\RegisteredPostedData;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use Yii;
use kartik\mpdf\Pdf;


class RailwayPostedDataController extends \yii\web\Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionPrint($id){
		//$this->layout='adminlayout';
		$request=Yii::$app->request;
		 if($request->isAjax){


		 }else{
		    $pdf = new Pdf([
        'mode' => Pdf::MODE_UTF8, // leaner size using standard fonts
        'orientation'=>'L',
        'filename' => 'railways.pdf',

        'content' =>$this->renderPartial('print'),
        'options' => [
            'title' => 'Labels',
            'subject' => 'Generating Labels'
        ],
        // 'methods' => [
        //     'SetHeader' => ['Generated By: Ritesh Singh PDF Component||Generated On: ' . date("r")],
        //     'SetFooter' => ['|Page {PAGENO}|'],
        // ]
    ]);
	}
    return $pdf->render();

	}
  public function actionSlip($id){
 // $this->layout='adminlayout';
  $request=Yii::$app->request;
   if($request->isAjax){


   }else{
      $pdf = new Pdf([
      'mode' => Pdf::MODE_UTF8, // leaner size using standard fonts
      'orientation'=>'L',

      'content' =>$this->renderPartial('forwarding'),
      'options' => [
          'title' => 'Sorwarding Slip',
          'subject' => 'forwarding Slips'
      ],
      // 'methods' => [
      //     'SetHeader' => ['Generated By: Ritesh Singh PDF Component||Generated On: ' . date("r")],
      //     'SetFooter' => ['|Page {PAGENO}|'],
      // ]
  ]);
}
  return $pdf->render();

}



}
