<?php

namespace backend\modules\circulation\controllers;
use backend\modules\circulation\models\RegisteredPostedData;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use Yii;
use kartik\mpdf\Pdf;

class RegisteredPostedDataController extends \yii\web\Controller
{



    public function actionIndex()
    {
    	//$this->layout='adminlayout';
        return $this->render('index');
    }
    public function actionPercentage($id)
    {
		if (Yii::app()->request->isAjaxRequest) {
		   $item = RegisteredPostedData::model()->findByPk($id); //obtain instance of object containing your function
		   echo $item->getBuildPercentage(); //to return value in ajax, simply echo it
		}
	}
	public function actionCreate(){
		return $this->render('index');
	}
	public function actionPrint($id){
		$this->layout='adminlayout';
		$request=Yii::$app->request;
		 if($request->isAjax){


		 }else{
		    $pdf = new Pdf([
        'mode' => Pdf::MODE_UTF8, // leaner size using standard fonts
        'orientation'=>'L',

        'content' => $this->renderPartial('print'),
        'options' => [
            'title' => 'Labels',
            'subject' => 'Generating Labels'
        ],
        // 'methods' => [
        //     'SetHeader' => ['Generated By: Ritesh Singh PDF Component||Generated On: ' . date("r")],
           // 'SetFooter' => ['|Page {PAGENO}|'],
        // ]
    ]);
	}
    return $pdf->render();

	}
  public function actionSlip($id){
   // $this->layout='adminlayout';
    $request=Yii::$app->request;
     if($request->isAjax){


     }else{
        $pdf = new Pdf([
        'mode' => Pdf::MODE_UTF8, // leaner size using standard fonts
        'orientation'=>'P',
        'cssInline' => 'table {
    border-collapse: collapse;
}

table, th, td {
    border: 1px solid black;
}', 

        'content' => $this->renderPartial('forwarding'),
        'options' => [
            'title' => 'Labels',
            'subject' => 'Generating Labels',
            'defaultheaderline' => 0,
            'defaultfooterline' => 0,
        ],
         'methods' => [
//             'SetHeader' => ['Generated By: Ritesh Singh PDF Component||Generated On: ' . date("r")],
             'SetFooter' => ['Page {PAGENO}'],
         ]
    ]);
  }
    return $pdf->render();

  }

	/**
     * Finds the RegisteredPostData model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return RegisteredPostData the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
	protected function findModel($id)
    {
        if (($model = RegisteredPostedData::find()->where(['post_id'=>$id])->all()) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}
